### PR TITLE
 refactor:  Changed to CMD to allow override

### PR DESCRIPTION
**Pull request by drodriguezcolli**
Changed ENTRYPOINT to CMD in the docker file to allow params overrride

### CODE REVIEW

**Comment by alexandrumd** [comment]
@dianarodriguezcolli why would we like to allow params override? Which use cases are we aiming? Thanks!

**Review by alexandrumd — COMMENTED** [review]
@dianarodriguezcolli why would we like to allow params override? Which use cases are we aiming? Thanks!

**Comment by EduardoSimon** [comment]
Hi @alexandrumd , I was pairing the fix with diana. By using CMD instead of ENTRYPOINT you can easily override the entry command of the container. The most typical use case for this is to use /bin/sh inside the container. So, for example, you could build it by:
` docker build -t treasure --target=test .`

and run bash to check the state of the container by:
`docker run -it --rm treasure /bin/bash`

Without the command, you need to change the entrypoint to empty doing:
` docker run --entrypoint='' -it --rm treasure /bin/bash`

Its not a great way of doing it

**Comment by alexandrumd** [comment]
> Hi @alexandrumd , I was pairing the fix with diana. By using CMD instead of ENTRYPOINT you can easily override the entry command of the container. The most typical use case for this is to use /bin/sh inside the container. So, for example, you could build it by: ` docker build -t treasure --target=test .`
> 
> and run bash to check the state of the container by: `docker run -it --rm treasure /bin/bash`
> 
> Without the command, you need to change the entrypoint to empty doing: ` docker run --entrypoint='' -it --rm treasure /bin/bash`
> 
> Its not a great way of doing it

thanks for the details! @sanchezpaco do you see any concerns with it?

**Comment by EduardoSimon** [comment]
Closing because this change would break the current interface of the docker container.
https://flywire.slack.com/archives/CB9618VFZ/p1667390365136689

**Pull request closed without merging**
